### ISSUE TITLE
Actualización de  logotipo de los sponsors*

### ISSUE THREAD

**Issue by osmaryasm** [RailsGirlsVE/pagweb#15]
Actualizado el logo de la asociación

**Comment by osmaryasm** [comment]
Acá se actualizó el logo de la Asociación aLabs* por el nuevo diseño

**Comment by Kyaalena-zz** [comment]
he agregado un nuevo logo en los sponsors, y el tamaño que tiene el logo de gnuve es el que deberían de tener los demás 

hay algo con el css que no les da el mismo tamaño

**Comment by bblanco93** [comment]
Se solucionó el problema del tamaño de los logos de los patrocinadores (todos poseen las mismas dimensiones)
