### ISSUE TITLE
Secciónde redes sociales

### ISSUE THREAD

**Issue by Kyaalena-zz** [RailsGirlsVE/pagweb#3]
Esta sección tiene mucha altura, el requerimiento es reducirla, logrando que entren más iconos de redes sociales, de tal manera que solo queden 2 filas.

**Comment by osmaryasm** [comment]
Acá solo hice un cambio de un icono de las redes sociales...

**Comment by bblanco93** [comment]
Se redujo el espacio entre los iconos de las redes sociales (quedando todas en dos filas)

**Comment by Kyaalena-zz** [comment]
fino, esta perfecto como quedo, vamos a cerrar el issues
