### ISSUE TITLE
Sección de servicios

### ISSUE THREAD

**Issue by Kyaalena-zz** [RailsGirlsVE/pagweb#4]
Falta agrear un servicio  o eliminar la columna vacia y reajustar la forma gráfica.

**Comment by osmaryasm** [comment]
Se hicieron cambios de medidas de los cuadros contenedores de los servicios, se eliminó la columna vacía...Acá en el branch respectivo se agregaron cambios en el portfolio, se le agregaron imágenes de los eventos, webinars y capsulas, y se editaron los titulos a los cuales hace referencia
