### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by Kyaalena-zz** [RailsGirlsVE/pagweb#5]
Mejorar la imagen agrandole algun estilo y tendencia 2018 

sugenrencias https://www.youtube.com/watch?v=oejFIAoLxe8&index=2&list=PLbfLuaN1UVEzZbF68gTZbNogvhHIWHrMK

**Comment by osmaryasm** [comment]
Cambiada la imagen del background y agregado un efecto duotono...Se le dió efecto parallax y cambiada la tipografía según tendencias web
